server:
  port: 8081

spring:
  application:
    name: parking-provider

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: treeparking-provider8080
    prefer-ip-address: true
